/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pav.tp1;

/**
 *
 * @author Gerardo
 */
public class Imitador extends javax.swing.JFrame {

    /** Creates new form Imitador */
    public Imitador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        originalLabel = new javax.swing.JLabel();
        panelOriginal1 = new javax.swing.JPanel();
        opcion1RadioButton = new javax.swing.JRadioButton();
        opción1CheckBox = new javax.swing.JCheckBox();
        textFieldOriginal = new javax.swing.JTextField();
        panelOriginal2 = new javax.swing.JPanel();
        opcion2RadioButton = new javax.swing.JRadioButton();
        opción2CheckBox = new javax.swing.JCheckBox();
        comboBoxOriginal = new javax.swing.JComboBox<>();
        panelOriginal3 = new javax.swing.JPanel();
        opcion3RadioButton = new javax.swing.JRadioButton();
        opción3CheckBox = new javax.swing.JCheckBox();
        spinnerOriginal = new javax.swing.JSpinner();
        separador = new javax.swing.JSeparator();
        espejoLabel = new javax.swing.JLabel();
        panelEspejo1 = new javax.swing.JPanel();
        opcion1RadioButtonEspejo = new javax.swing.JRadioButton();
        opción1CheckBoxEspejo = new javax.swing.JCheckBox();
        textFieldEspejo = new javax.swing.JTextField();
        panelEspejo2 = new javax.swing.JPanel();
        opcion2RadioButtonEspejo = new javax.swing.JRadioButton();
        opción2CheckBoxEspejo = new javax.swing.JCheckBox();
        comboBoxEspejo = new javax.swing.JComboBox<>();
        panelEspejo3 = new javax.swing.JPanel();
        opcion3RadioButtonEspejo = new javax.swing.JRadioButton();
        opción3CheckBoxEspejo = new javax.swing.JCheckBox();
        spinnerEspejo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 20));

        originalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        originalLabel.setText("Original");
        originalLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        getContentPane().add(originalLabel);

        panelOriginal1.setPreferredSize(new java.awt.Dimension(600, 50));
        panelOriginal1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion1RadioButton.setText("Opción 1");
        opcion1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1RadioButtonActionPerformed(evt);
            }
        });
        panelOriginal1.add(opcion1RadioButton);

        opción1CheckBox.setText("Opción 4");
        opción1CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opción1CheckBoxActionPerformed(evt);
            }
        });
        panelOriginal1.add(opción1CheckBox);

        textFieldOriginal.setPreferredSize(new java.awt.Dimension(150, 22));
        textFieldOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldOriginalKeyTyped(evt);
            }
        });
        panelOriginal1.add(textFieldOriginal);

        getContentPane().add(panelOriginal1);

        panelOriginal2.setPreferredSize(new java.awt.Dimension(600, 50));
        panelOriginal2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion2RadioButton.setText("Opción 2");
        opcion2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2RadioButtonActionPerformed(evt);
            }
        });
        panelOriginal2.add(opcion2RadioButton);

        opción2CheckBox.setText("Opción 5");
        opción2CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opción2CheckBoxActionPerformed(evt);
            }
        });
        panelOriginal2.add(opción2CheckBox);

        comboBoxOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxOriginal.setPreferredSize(new java.awt.Dimension(150, 22));
        comboBoxOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOriginalActionPerformed(evt);
            }
        });
        panelOriginal2.add(comboBoxOriginal);

        getContentPane().add(panelOriginal2);

        panelOriginal3.setPreferredSize(new java.awt.Dimension(600, 50));
        panelOriginal3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion3RadioButton.setText("Opción 3");
        opcion3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3RadioButtonActionPerformed(evt);
            }
        });
        panelOriginal3.add(opcion3RadioButton);

        opción3CheckBox.setText("Opción 6");
        opción3CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opción3CheckBoxActionPerformed(evt);
            }
        });
        panelOriginal3.add(opción3CheckBox);

        spinnerOriginal.setPreferredSize(new java.awt.Dimension(150, 22));
        spinnerOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerOriginalStateChanged(evt);
            }
        });
        panelOriginal3.add(spinnerOriginal);

        getContentPane().add(panelOriginal3);

        separador.setPreferredSize(new java.awt.Dimension(600, 2));
        getContentPane().add(separador);

        espejoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        espejoLabel.setText("Espejo");
        espejoLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        getContentPane().add(espejoLabel);

        panelEspejo1.setPreferredSize(new java.awt.Dimension(600, 50));
        panelEspejo1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion1RadioButtonEspejo.setText("Opción 1");
        opcion1RadioButtonEspejo.setEnabled(false);
        panelEspejo1.add(opcion1RadioButtonEspejo);

        opción1CheckBoxEspejo.setText("Opción 4");
        opción1CheckBoxEspejo.setEnabled(false);
        panelEspejo1.add(opción1CheckBoxEspejo);

        textFieldEspejo.setEnabled(false);
        textFieldEspejo.setPreferredSize(new java.awt.Dimension(150, 22));
        panelEspejo1.add(textFieldEspejo);

        getContentPane().add(panelEspejo1);

        panelEspejo2.setPreferredSize(new java.awt.Dimension(600, 50));
        panelEspejo2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion2RadioButtonEspejo.setText("Opción 2");
        opcion2RadioButtonEspejo.setEnabled(false);
        panelEspejo2.add(opcion2RadioButtonEspejo);

        opción2CheckBoxEspejo.setText("Opción 5");
        opción2CheckBoxEspejo.setToolTipText("");
        opción2CheckBoxEspejo.setEnabled(false);
        panelEspejo2.add(opción2CheckBoxEspejo);

        comboBoxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEspejo.setEnabled(false);
        comboBoxEspejo.setPreferredSize(new java.awt.Dimension(150, 22));
        panelEspejo2.add(comboBoxEspejo);

        getContentPane().add(panelEspejo2);

        panelEspejo3.setMinimumSize(new java.awt.Dimension(600, 50));
        panelEspejo3.setPreferredSize(new java.awt.Dimension(600, 50));
        panelEspejo3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 20));

        opcion3RadioButtonEspejo.setText("Opción 3");
        opcion3RadioButtonEspejo.setToolTipText("");
        opcion3RadioButtonEspejo.setEnabled(false);
        panelEspejo3.add(opcion3RadioButtonEspejo);

        opción3CheckBoxEspejo.setText("Opción 6");
        opción3CheckBoxEspejo.setEnabled(false);
        panelEspejo3.add(opción3CheckBoxEspejo);

        spinnerEspejo.setEnabled(false);
        spinnerEspejo.setPreferredSize(new java.awt.Dimension(150, 22));
        panelEspejo3.add(spinnerEspejo);

        getContentPane().add(panelEspejo3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1RadioButtonActionPerformed
        opcion1RadioButtonEspejo.setSelected(opcion1RadioButton.isSelected());  
    }//GEN-LAST:event_opcion1RadioButtonActionPerformed

    private void opcion2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2RadioButtonActionPerformed
       opcion2RadioButtonEspejo.setSelected(opcion2RadioButton.isSelected());  
    }//GEN-LAST:event_opcion2RadioButtonActionPerformed

    private void opcion3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3RadioButtonActionPerformed
      opcion3RadioButtonEspejo.setSelected(opcion3RadioButton.isSelected());  
    }//GEN-LAST:event_opcion3RadioButtonActionPerformed

    private void opción1CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opción1CheckBoxActionPerformed
      opción1CheckBoxEspejo.setSelected(opción1CheckBox.isSelected());  
    }//GEN-LAST:event_opción1CheckBoxActionPerformed

    private void opción2CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opción2CheckBoxActionPerformed
      opción2CheckBoxEspejo.setSelected(opción2CheckBox.isSelected());  
    }//GEN-LAST:event_opción2CheckBoxActionPerformed

    private void opción3CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opción3CheckBoxActionPerformed
     opción3CheckBoxEspejo.setSelected(opción3CheckBox.isSelected());  
    }//GEN-LAST:event_opción3CheckBoxActionPerformed

    private void textFieldOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldOriginalKeyTyped
        textFieldEspejo.setText(textFieldOriginal.getText());
    }//GEN-LAST:event_textFieldOriginalKeyTyped

    private void comboBoxOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOriginalActionPerformed
        comboBoxEspejo.setSelectedItem(comboBoxOriginal.getSelectedItem());
    }//GEN-LAST:event_comboBoxOriginalActionPerformed

    private void spinnerOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerOriginalStateChanged
        spinnerEspejo.setValue(spinnerOriginal.getValue());
    }//GEN-LAST:event_spinnerOriginalStateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxEspejo;
    private javax.swing.JComboBox<String> comboBoxOriginal;
    private javax.swing.JLabel espejoLabel;
    private javax.swing.JRadioButton opcion1RadioButton;
    private javax.swing.JRadioButton opcion1RadioButtonEspejo;
    private javax.swing.JRadioButton opcion2RadioButton;
    private javax.swing.JRadioButton opcion2RadioButtonEspejo;
    private javax.swing.JRadioButton opcion3RadioButton;
    private javax.swing.JRadioButton opcion3RadioButtonEspejo;
    private javax.swing.JCheckBox opción1CheckBox;
    private javax.swing.JCheckBox opción1CheckBoxEspejo;
    private javax.swing.JCheckBox opción2CheckBox;
    private javax.swing.JCheckBox opción2CheckBoxEspejo;
    private javax.swing.JCheckBox opción3CheckBox;
    private javax.swing.JCheckBox opción3CheckBoxEspejo;
    private javax.swing.JLabel originalLabel;
    private javax.swing.JPanel panelEspejo1;
    private javax.swing.JPanel panelEspejo2;
    private javax.swing.JPanel panelEspejo3;
    private javax.swing.JPanel panelOriginal1;
    private javax.swing.JPanel panelOriginal2;
    private javax.swing.JPanel panelOriginal3;
    private javax.swing.JSeparator separador;
    private javax.swing.JSpinner spinnerEspejo;
    private javax.swing.JSpinner spinnerOriginal;
    private javax.swing.JTextField textFieldEspejo;
    private javax.swing.JTextField textFieldOriginal;
    // End of variables declaration//GEN-END:variables

}
