/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pav.tp1;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public class MiniEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form MiniEncuesta
     */
    public MiniEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        descripcionSO = new javax.swing.JLabel();
        windows = new javax.swing.JRadioButton();
        linux = new javax.swing.JRadioButton();
        mac = new javax.swing.JRadioButton();
        separador1 = new javax.swing.JSeparator();
        descripcionEspecialidad = new javax.swing.JLabel();
        programacion = new javax.swing.JCheckBox();
        disenoGrafico = new javax.swing.JCheckBox();
        administracion = new javax.swing.JCheckBox();
        separator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        totalHoras = new javax.swing.JLabel();
        sliderHoras = new javax.swing.JSlider();
        generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Encuesta");

        descripcionSO.setText("Elige un sistema operativo");

        windows.setText("Windows");
        windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsActionPerformed(evt);
            }
        });

        linux.setText("Linux");
        linux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linuxActionPerformed(evt);
            }
        });

        mac.setText("Mac");
        mac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macActionPerformed(evt);
            }
        });

        descripcionEspecialidad.setText("Elige tu especialidad");

        programacion.setText("Programación");

        disenoGrafico.setText("Diseño gráfico");

        administracion.setText("Administración");

        jLabel1.setText("Horas que dedicas en el ordenador");

        totalHoras.setText("0");

        sliderHoras.setMaximum(10);
        sliderHoras.setPaintTicks(true);
        sliderHoras.setValue(0);
        sliderHoras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderHoras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHorasStateChanged(evt);
            }
        });

        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separador1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(separator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(programacion)
                                    .addComponent(disenoGrafico)
                                    .addComponent(administracion)
                                    .addComponent(descripcionEspecialidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(linux)
                                    .addComponent(windows)
                                    .addComponent(descripcionSO)
                                    .addComponent(mac)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(generar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(totalHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sliderHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel1))))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(descripcionSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(windows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mac)
                .addGap(7, 7, 7)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(descripcionEspecialidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disenoGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administracion)
                .addGap(16, 16, 16)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHoras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsActionPerformed
        windows.setSelected(true);
        linux.setSelected(false);
        mac.setSelected(false);
    }//GEN-LAST:event_windowsActionPerformed

    private void linuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linuxActionPerformed
        windows.setSelected(false);
        linux.setSelected(true);
        mac.setSelected(false);
    }//GEN-LAST:event_linuxActionPerformed

    private void macActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macActionPerformed
        windows.setSelected(false);
        linux.setSelected(false);
        mac.setSelected(true);
    }//GEN-LAST:event_macActionPerformed

    private void sliderHorasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHorasStateChanged
        int total = sliderHoras.getValue();
        totalHoras.setText(String.valueOf(total));
    }//GEN-LAST:event_sliderHorasStateChanged
    
    private String sistemaOperativoSeleccionado() {
        if (windows.isSelected()) {
            return windows.getText();
        }
        if (linux.isSelected()) {
            return linux.getText();
        }
        if (mac.isSelected()) {
            return mac.getText();
        }
        return "Sin selección";
    }
    
    private String especialidadSeleccionada() {
        StringBuilder seleccion = new StringBuilder();  
        if (programacion.isSelected()) {
            seleccion.append("- ").append(programacion.getText()).append("\n");
        }
        if (disenoGrafico.isSelected()) {
            seleccion.append("- ").append(disenoGrafico.getText()).append("\n");
        }
        if (administracion.isSelected()) {
            seleccion.append("- ").append(administracion.getText()).append("\n");
        }
        if (seleccion.length() == 0) {
            return "Sin selección";
        }
        return "\n" + seleccion.toString();
    }
    
    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
       String seleccion = "La selección del usuario fue:\n"
               + "\t* Sistema operativo: " + sistemaOperativoSeleccionado()
               + "\n\t* Sus especialidades son: " + especialidadSeleccionada()
               + "\n\t* Horas dedicadas en el ordenador: "
               + totalHoras.getText() + "hrs.";
       
       JOptionPane.showMessageDialog(this, seleccion);
    }//GEN-LAST:event_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administracion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descripcionEspecialidad;
    private javax.swing.JLabel descripcionSO;
    private javax.swing.JCheckBox disenoGrafico;
    private javax.swing.JButton generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton linux;
    private javax.swing.JRadioButton mac;
    private javax.swing.JCheckBox programacion;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSlider sliderHoras;
    private javax.swing.JLabel totalHoras;
    private javax.swing.JRadioButton windows;
    // End of variables declaration//GEN-END:variables
}
