/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pav.tp1;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public class Peliculas extends javax.swing.JFrame {

    /**
     * Creates new form Peliculas
     */
    public Peliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        tituloPelicula = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        listaPelicula = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        descripcionPeliculas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Películas");

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contenedor.add(tituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 55, 146, -1));

        descripcion.setText("Escribe el título de una película");
        contenedor.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 30, -1, -1));

        listaPelicula.setEnabled(false);
        listaPelicula.setMinimumSize(new java.awt.Dimension(6, 20));
        contenedor.add(listaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 55, 166, -1));

        agregar.setText("Añadir");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        contenedor.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 93, -1, -1));

        descripcionPeliculas.setText("Películas");
        contenedor.add(descripcionPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String pelicula = tituloPelicula.getText();        
        
        if (pelicula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe el título de una película");
        } else {
            // Habilita el combo
            if (!listaPelicula.isEnabled()) {
                listaPelicula.setEnabled(true);
            }
            // Agrega la película a la lista        
            listaPelicula.addItem(pelicula);

            // Setea el último item agregado a mostrarse en el combo
            int ultimo = listaPelicula.getItemCount() -1;
            listaPelicula.setSelectedIndex(ultimo);

            tituloPelicula.setText("");
        }
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel descripcionPeliculas;
    private javax.swing.JComboBox<String> listaPelicula;
    private javax.swing.JTextField tituloPelicula;
    // End of variables declaration//GEN-END:variables
}
