package com.tp.vista;

import com.tp.controlador.ControllerArticulo;
import com.tp.controlador.ControllerMarca;
import com.tp.modelo.Articulo;
import com.tp.modelo.Marca;
import com.tp.util.HibernateUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Integrantes:
 *
 * @author Baudino Gerardo
 * @author Poleri Franco
 * @author Pozzutto Romina
 */
public class GestionadorArticulo extends javax.swing.JFrame {

    private final ControllerArticulo controllerArticulo;
    private final ControllerMarca controllerMarca;
    private final SessionFactory sessionFactory;
    private final Session session;

    private List<Articulo> articulos;
    private List<Marca> marcas;
    private int filaSeleccionada = 0;

    /**
     * Creates new form GestionadorArticulo
     */
    public GestionadorArticulo() {
        controllerArticulo = new ControllerArticulo();
        controllerMarca = new ControllerMarca();
        sessionFactory = HibernateUtil.getSessionFactory();
        session = sessionFactory.openSession();
        articulos = new ArrayList<>();
        marcas = new ArrayList<>();

        initComponents();
        cargarArticulos();
        cargarMarcas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        jLabelPrecioCosto = new javax.swing.JLabel();
        jTextFieldPrecioCosto = new javax.swing.JTextField();
        jLabelPrecioVenta = new javax.swing.JLabel();
        jTextFieldPrecioVenta = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        jMenuBarSalir = new javax.swing.JMenuBar();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(102, 153, 255));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Gestionador de Artículos");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripción", "Precio Costo", "Precio Venta", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArticulos.setToolTipText("");
        jTableArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArticulos);

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabelCodigo.setText("Código:");

        jLabelNombre.setText("Nombre:");

        jLabelDescripcion.setText("Descripción:");

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setEnabled(false);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabelPrecioCosto.setText("Precio de Costo: $");

        jLabelPrecioVenta.setText("Precio de Venta: $");

        jLabelMarca.setText("Marca:");

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin especificar" }));

        jMenuSalir.setText("Opciones");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBarSalir.add(jMenuSalir);

        setJMenuBar(jMenuBarSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonActualizar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNombre)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelPrecioCosto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelPrecioVenta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecioCosto)
                    .addComponent(jTextFieldPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecioVenta)
                    .addComponent(jTextFieldPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarca)
                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String requeridos = evaluarDatosRequeridos();
        if (requeridos.isEmpty()) {
            agregar();
        } else {
            JOptionPane.showMessageDialog(this, requeridos);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        String requeridos = evaluarDatosRequeridos();
        if (requeridos.isEmpty()) {
            borrarFila(filaSeleccionada);
            agregar();
            
            jButtonActualizar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, requeridos);
        }        
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTableArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArticulosMouseClicked
        jButtonActualizar.setEnabled(true);

        filaSeleccionada = jTableArticulos.rowAtPoint(evt.getPoint());
        Articulo articuloSeleccionado = articulos.get(filaSeleccionada);

        jTextFieldCodigo.setText(String.valueOf(articuloSeleccionado.getCodigo()));
        jTextFieldNombre.setText(articuloSeleccionado.getNombre());
        jTextFieldDescripcion.setText(articuloSeleccionado.getDescripcion());
        jTextFieldPrecioCosto.setText(String.valueOf(articuloSeleccionado.getPrecioCosto()));
        jTextFieldPrecioVenta.setText(String.valueOf(articuloSeleccionado.getPrecioVenta()));

        Marca marca = articuloSeleccionado.getMarca();
        if (marca == null) {
            jComboBoxMarcas.setSelectedIndex(0);
        } else {
            int indexOf = marcas.indexOf(marca);
            jComboBoxMarcas.setSelectedIndex(indexOf + 1);
        }
    }//GEN-LAST:event_jTableArticulosMouseClicked

    private void cargarArticulos() {
        articulos = controllerArticulo.obtener(session);
        articulos.forEach(articulo -> {
            agregarFila(articulo);
        });
    }

    private void cargarMarcas() {
        marcas = controllerMarca.obtener(session);
        marcas.forEach(marca -> {
            jComboBoxMarcas.addItem(marca.getDescripcion());
        });
    }

    private String evaluarDatosRequeridos() {
        if (jTextFieldCodigo.getText().isEmpty()) {
            return "Código es un dato requerido";
        }
        if (jTextFieldNombre.getText().isEmpty()) {
            return "Nombre es un dato requerido";
        }
        if (jTextFieldDescripcion.getText().isEmpty()) {
            return "Descripción es un dato requerido";
        }
        if (jTextFieldPrecioCosto.getText().isEmpty()) {
            return "Precio de Costo es un dato requerido";
        }
        if (jTextFieldPrecioVenta.getText().isEmpty()) {
            return "Precio de Venta es un dato requerido";
        }
        return "";
    }

    private void agregar() {
        String descripcion = jComboBoxMarcas.getSelectedItem().toString();
        Marca marca = marcaSegunDescripcion(descripcion);

        Articulo articulo = new Articulo(
                Integer.valueOf(jTextFieldCodigo.getText().trim()),
                jTextFieldNombre.getText().trim(),
                jTextFieldDescripcion.getText().trim(),
                Double.valueOf(jTextFieldPrecioCosto.getText().trim()),
                Double.valueOf(jTextFieldPrecioVenta.getText().trim()),
                marca
        );

        if (articulos.contains(articulo)) {
            JOptionPane.showMessageDialog(this, "El Artículo que desea agregar ya existe");
        } else {
            agregarFila(articulo);

            articulos.add(articulo);
            controllerArticulo.registrar(session, articulo);
        }
    }

    private void agregarFila(Articulo articulo) {
        String[] fila = {
            String.valueOf(articulo.getCodigo()),
            articulo.getNombre(),
            articulo.getDescripcion(),
            String.valueOf(articulo.getPrecioCosto()),
            String.valueOf(articulo.getPrecioVenta()),
            articulo.getMarca() != null ? articulo.getMarca().getDescripcion() : "Sin especificar"
        };
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableArticulos.getModel();
        defaultTableModel.addRow(fila);
    }
    
    private void borrarFila(int indice) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableArticulos.getModel();
        defaultTableModel.removeRow(indice);
    }

    private Marca marcaSegunDescripcion(String descripcion) {
        Marca resultado = new Marca(1, "Sin especificar");
        for (Marca marca : marcas) {
            if (marca.getDescripcion().equals(descripcion)) {
                resultado = marca;
                break;
            }
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecioCosto;
    private javax.swing.JLabel jLabelPrecioVenta;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBarSalir;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecioCosto;
    private javax.swing.JTextField jTextFieldPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
